# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: "O.P. Jindal Global University"
    description: "Dr. Roopendra Roopak is an academic specializing in customer engagement, brand communities, and sustainable consumer behavior."
    #twitter: 'RoopendraRoopak'  # Optional: Add your real Twitter/X handle
  analytics:
    google_analytics: 'G-Y7HMS4B2CG'  # Optional: Add your GA code
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Dr. Roopendra Roopak"

# Site footer
footer:
  copyright:
    notice: '© {year} Dr. Roopendra Roopak. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
