# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'O.P. Jindal Global University'
    description: Dr. Roopendra Roopak is an academic and Assistant Professor of Marketing at O.P. Jindal Global University specializing in customer engagement, brand communities, and sustainable consumer behaviour.
    twitter: roopakRoopendra  # Optional: Add your real Twitter/X handle
    image: /authors/roopendra-roopak/avatar.jpg

    keywords:
      - Marketing
      - customer engagement
      - online brand communities
      - sustainable consumption
      - consumer psychology
      - behavioural marketing
      - game theory in marketing
      - Roopendra Roopak
      - O.P. Jindal Global University
      - Assistant Professor of Marketing
      - Jindal Global Business School
      - JGBS
    
    sameAs:
      - https://www.linkedin.com/in/roopendra-roopak/
      - https://scholar.google.com/citations?user=stFFZ5oAAAAJ
      - https://www.researchgate.net/profile/Roopendra-Roopak
      - https://orcid.org/0000-0001-7122-2434
      - https://x.com/roopakRoopendra
      - https://www.instagram.com/dr.roopendra.roopak/
  
  analytics:
    google_analytics: 'G-Y7HMS4B2CG'  # Optional: Add your GA code
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: Yjg-u7ibITaOW0AMKNB30pi2ozH1LZYmIndFKZqb1Cs
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Dr. Roopendra Roopak"

# Site footer
footer:
  copyright:
    notice: '© {year} Dr. Roopendra Roopak. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
